// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(RecruitmentAgencyContext))]
    [Migration("20241113211422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkill", (string)null);
                });

            modelBuilder.Entity("JobVacancySkill", b =>
                {
                    b.Property<int>("JobVacancyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_vacancy_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.HasKey("JobVacancyId", "SkillId");

                    b.HasIndex("JobVacancyId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobVacancySkill", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_info");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("current_status");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT")
                        .HasColumnName("education");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Resume")
                        .HasColumnType("TEXT")
                        .HasColumnName("resume");

                    b.Property<string>("WorkExperience")
                        .HasColumnType("TEXT")
                        .HasColumnName("work_experience");

                    b.HasKey("Id");

                    b.ToTable("Candidate", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CompanySize")
                        .HasColumnType("TEXT")
                        .HasColumnName("company_size");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("industry");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<string>("Email")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email");

                    b.HasIndex("Phone");

                    b.ToTable("Employer", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.HiringEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CandidateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT")
                        .HasColumnName("feedback");

                    b.Property<int?>("RecruiterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recruiter_id");

                    b.Property<int?>("VacancyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("RecruiterId");

                    b.HasIndex("VacancyId");

                    b.ToTable("HiringEvent", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.HiringEventStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<int>("HiringEventId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hiring_event_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("HiringEventId");

                    b.ToTable("HiringEventStage", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.JobVacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("JobDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_description");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_title");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<int?>("RecruiterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("Requirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("requirements");

                    b.Property<double?>("Salary")
                        .HasColumnType("REAL")
                        .HasColumnName("salary");

                    b.Property<string>("VacancyStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Open")
                        .HasColumnName("vacancy_status");

                    b.HasKey("Id");

                    b.HasIndex("RecruiterId");

                    b.ToTable("JobVacancy", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Recruiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_info");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("specialization");

                    b.Property<int>("SuccessfulClosures")
                        .HasColumnType("INTEGER")
                        .HasColumnName("successful_closures");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Recruiter", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.HasOne("WebApp.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobVacancySkill", b =>
                {
                    b.HasOne("WebApp.Models.JobVacancy", null)
                        .WithMany()
                        .HasForeignKey("JobVacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Models.Employer", b =>
                {
                    b.HasOne("WebApp.Models.Company", "Company")
                        .WithMany("Employers")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebApp.Models.HiringEvent", b =>
                {
                    b.HasOne("WebApp.Models.Candidate", "Candidate")
                        .WithMany("HiringEvents")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApp.Models.Recruiter", "Recruiter")
                        .WithMany("HiringEvents")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApp.Models.JobVacancy", "Vacancy")
                        .WithMany("HiringEvents")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Candidate");

                    b.Navigation("Recruiter");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("WebApp.Models.HiringEventStage", b =>
                {
                    b.HasOne("WebApp.Models.HiringEvent", "HiringEvent")
                        .WithMany("HiringEventStages")
                        .HasForeignKey("HiringEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HiringEvent");
                });

            modelBuilder.Entity("WebApp.Models.JobVacancy", b =>
                {
                    b.HasOne("WebApp.Models.Recruiter", "Recruiter")
                        .WithMany("JobVacancies")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("WebApp.Models.Recruiter", b =>
                {
                    b.HasOne("WebApp.Models.Company", "Company")
                        .WithMany("Recruiters")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebApp.Models.Candidate", b =>
                {
                    b.Navigation("HiringEvents");
                });

            modelBuilder.Entity("WebApp.Models.Company", b =>
                {
                    b.Navigation("Employers");

                    b.Navigation("Recruiters");
                });

            modelBuilder.Entity("WebApp.Models.HiringEvent", b =>
                {
                    b.Navigation("HiringEventStages");
                });

            modelBuilder.Entity("WebApp.Models.JobVacancy", b =>
                {
                    b.Navigation("HiringEvents");
                });

            modelBuilder.Entity("WebApp.Models.Recruiter", b =>
                {
                    b.Navigation("HiringEvents");

                    b.Navigation("JobVacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
